config/routes.rb
Rails.application.routes.draw do
  root to: "portfolios#index"

  resources :portfolios , :except => [:new] do
  	collection do
  		get :import_form
  		post :import
  	end
  end
end

app/models/portfolio.rb
class Portfolio

  attr_accessor :ticket_name, :purchase_date, :purchase_price, :purchase_qty

  def initialize(line)
  	begin
	  	portfolio_data = line.split(",")
	  	#raise "unsufficient data" if portfolio_data.length != 3
  		@ticket_name = portfolio_data[0]
  		@purchase_date = Date.strptime(portfolio_data[1], "%d/%m/%Y") 
  		@purchase_price = Float(portfolio_data[2])
  		@purchase_qty = Integer(portfolio_data[3])
  	rescue => error
			Rails.logger.error(" line format issue in csv file : #{line}")
      raise "Line format issue in csv file: Please check line => #{line}"
		end
  end

  def calculate_profit_loss(current_price)
    return 0 if current_price.nil? || current_price < 0
    return ((current_price - self.purchase_price) * self.purchase_qty).round(2) 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController


	def index
		@portfolios = Rails.cache.read(PortfolioManagement::FILE_FOR_PORTFOLIO) || {}
		shareprices = Rails.cache.read(PortfolioManagement::FILE_FOR_SHAREPRICE) || {}	
		@current_prices = shareprices.present? ? shareprices[Date.today.strftime('%d/%m/%Y')] : {}
	end

	def import_form
		@file_for = params[:file_for].blank? ? PortfolioManagement::FILE_FOR_PORTFOLIO : PortfolioManagement::FILE_FOR_SHAREPRICE
	end

	def import
		file_data = params[:file]
		if file_data.content_type == "text/csv" && file_data.respond_to?(:read)
		  portfolio_data = file_data.read
		  success, error_msg = 	read_create_list(portfolio_data, params[:file_for])	
		else
		  error_msg = "Please upload only csv file."
		end	
		if !success
			render json: {error: error_msg}, status: 400
		else
			render json: {redirect_url: portfolios_url}, status: :ok
		end
	end

	def show
		@profile = params[:id]
		@portfolios = Rails.cache.read(PortfolioManagement::FILE_FOR_PORTFOLIO) || {}
		@myportfolio = @portfolios[@profile]
		shareprices = Rails.cache.read(PortfolioManagement::FILE_FOR_SHAREPRICE) || {}	
		@current_prices = shareprices.present? ? shareprices[Date.today.strftime('%d/%m/%Y')] : {}
	end

	private
	def read_create_list(contents, list_for)
		portfolios_data = Rails.cache.read(PortfolioManagement::FILE_FOR_PORTFOLIO) || {}
		key = "Portfolio_#{portfolios_data.keys.length + 1}"
		portfolios_data[key] = []
		begin
			contents.split("\n").each do | line|
				next if line.split(",").reject{|r| r.blank?}.blank?				
				if list_for == PortfolioManagement::FILE_FOR_SHAREPRICE 
	 			  build_share_hash(line) unless line.start_with?("Ticket name")
				else
					portfolios_data[key] << Portfolio.new(line) unless line.start_with?("Ticket name")
				end			
			end		
		rescue => error
			Rails.logger.error(" line format issue: #{error.message}")
			return false, " #{error.message}"
		end	
		Rails.cache.write("#{list_for}",portfolios_data ) if list_for == PortfolioManagement::FILE_FOR_PORTFOLIO  

		return true
	end

	def build_share_hash(line)
		shareprices = Rails.cache.read(PortfolioManagement::FILE_FOR_SHAREPRICE) || {}
		begin
	  	share_data = line.split(",")	  
  		ticket_name = share_data[0]
  		date = Date.strptime(share_data[1], '%d/%m/%Y')
  		price = share_data[2].to_f
  		shareprices[date.strftime('%d/%m/%Y')] = {} if shareprices[date.strftime('%d/%m/%Y')].blank?
  		shareprices[date.strftime('%d/%m/%Y')].merge!(ticket_name => price)
  	rescue => error
			Rails.logger.error("Line format issue in csv file: #{line}")
			raise "Line format issue in csv file: Please check line => #{line}"
		end
		
		Rails.cache.write(PortfolioManagement::FILE_FOR_SHAREPRICE, shareprices) 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/protfolios_helper.rb
module ProtfoliosHelper
end

app/helpers/share_price_helper.rb
module SharePriceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProtfolioManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand page-scroll" href="#page-top">Portfolio Manager</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">          
        <li><%= link_to "Portfolio details", portfolios_path %> </li>
        <li><%= link_to "Upload Portfolio", import_form_portfolios_path %> </li>
        <li><%= link_to "Upload Current Price", import_form_portfolios_path(file_for: 'shareprice') %> </li>           
      </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
  </nav>
  <%= content_tag(:div, flash[:error], :class => "alert alert-danger", :style => "#{flash[:error].present? ? '' : 'display:none' }") %>
  <%= content_tag(:div, flash[:success], :class => "alert alert-success", :style => "#{flash[:error].present? ? '' : 'display:none' }") %>

  <%= yield %>

</body>
</html>

app/views/portfolios/import_form.html.erb
<header>
	<div class="header-content">
		<div class="header-content-inner">
			<% if @file_for == PortfolioManagement::FILE_FOR_PORTFOLIO %>
				<h3>Upload your Portfolios:</h3>
			<% else %>
				<h3>Upload current Share Price:</h3>
			<% end %>
		</div>
	</div>
</header>
<section id="uploader">
	<div class="container">
			<button type="button" id="file_upload" class="btn btn-default spacing">
			<div><span> Select File </span></div>
			<% url = url_for controller: "portfolios", action: "import" %>
			<input id="fileupload" type="file" name="file" data-url= <%= url %>  class="fileuploadInput" multiple="false"  accept=".csv" accepted_file_types="text/csv">
			<input type="hidden" id="file_for" name="file_for" value='<%= @file_for %>'/>
			</button>
			<div class="spacing"></div>
			<div id="upload-progress">
				<span>filename</span>
				<div class="progress">
					<div class="progress-bar" role="progressbar">
						<span class="sr-only">70% Complete</span>
					</div>
				</div>
			</div>
	</div>
</section>

app/views/portfolios/index.html.erb
<header>
	<div class="header-content">
		<div class="header-content-inner">
			<h3>Your Portfolios</h3>
		</div>
	</div>
</header>
<section id="services">
	<div class="container">
		<% if @portfolios.blank? %>
			<h4> Portfolios not available. </h4>
		<% else %>
		  <% @portfolios.each do |key, portfolios| %>
			  <div class="main-portfolios" >
				  <h3> <%= link_to key.gsub("_", " "),portfolio_path(key) %></h3>
				  <% portfolios.each do | portfolio|  %>
					  <% tooltip = "Purchase Date: #{portfolio.purchase_date.strftime('%B %d %Y')} \n Purchase Quantity: #{portfolio.purchase_qty}" %>
					  <div class="portfolio-container" data-toggle="tooltip" title="<%= tooltip %>">
					  	<div>
					  		<span class="title"> <%= portfolio.ticket_name %></span>
					  		<span class="cost right"><%= portfolio.purchase_price %></span>
					  	</div>
						  <% if @current_prices.present? && @current_prices[portfolio.ticket_name] %>
						  	<% loss = portfolio.calculate_profit_loss(@current_prices[portfolio.ticket_name]) %>
						  	<span class="loss <%= 'hidden' if loss.nil? %> <%= 'green' if loss >= 0 %>"  > 
							  	<%= loss %>
						  	</span>
						  <% end %>
				  	</div>
				  <% end %>
			  </div>
		  <% end %>
		<% end %>
	</div>
</section>

app/views/portfolios/show.html.erb
<header>
	<div class="header-content">
		<div class="header-content-inner">
			<h3>Portfolio Chart for: <%= @profile.gsub("_", " ") %></h3>
		</div>
	</div>
</header>
<section id="services">
	<div class="container">
		<% if @portfolios.blank? || @current_prices.blank? %>
		<h4> Portfolio chart not available. </h4>
		<% else %>
		<div id="chart-container" >
			<script>
			  var datax = <%= @myportfolio.collect(&:ticket_name).to_json.html_safe %>
			  var data = [];
			  <% @myportfolio.each do |portfolio| %>
			    <% profit_loss = portfolio.calculate_profit_loss(@current_prices[portfolio.ticket_name]) %>
			    <% color =  profit_loss >= 0 ? "#41C159" : "#C32F2F" %>
			    data.push({ name: '<%= portfolio.ticket_name %>', y: <%= profit_loss %>, color: '<%= color %>'});
			  <% end %>
					barchart.init(datax, data, '<%= @profile %>');
			</script>
		</div>
		<% end %>
	</div>
</section>